version: "3.4"

services:
  frontend:
    container_name: frontend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    networks:
      - try-on-gateway

networks:
  try-on-gateway:
    external: true
